services:
  - type: web
    name: react-purity-api
    env: python
    buildCommand: cd api-server-django && ./build.sh
    startCommand: cd api-server-django && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: 0
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: react-purity-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        sync: false

databases:
  - name: react-purity-db
    databaseName: reactpurity
    user: reactpurity_user
    plan: free

